// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzXM96tGACeKeHkdEjEDZBzM2hn6fph9M',
    appId: '1:51585534438:web:4ba3d07e22cd21c869ae27',
    messagingSenderId: '51585534438',
    projectId: 'social-app-b4202',
    authDomain: 'social-app-b4202.firebaseapp.com',
    storageBucket: 'social-app-b4202.appspot.com',
    measurementId: 'G-ZLKKDHWY0Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEaC6hRJaZIU84sGGhOVnYxUgVhhkgUQg',
    appId: '1:51585534438:android:f7c1f2535786b92669ae27',
    messagingSenderId: '51585534438',
    projectId: 'social-app-b4202',
    storageBucket: 'social-app-b4202.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-piu4Qb9MIUD24DgqJljxkNGzV2XVbbs',
    appId: '1:51585534438:ios:9593a4e7023ed31169ae27',
    messagingSenderId: '51585534438',
    projectId: 'social-app-b4202',
    storageBucket: 'social-app-b4202.appspot.com',
    androidClientId: '51585534438-i3k9dkpgrts1e7la7n0j67ivt5te5icb.apps.googleusercontent.com',
    iosBundleId: 'com.example.sociallApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-piu4Qb9MIUD24DgqJljxkNGzV2XVbbs',
    appId: '1:51585534438:ios:383d11b9242a394969ae27',
    messagingSenderId: '51585534438',
    projectId: 'social-app-b4202',
    storageBucket: 'social-app-b4202.appspot.com',
    androidClientId: '51585534438-i3k9dkpgrts1e7la7n0j67ivt5te5icb.apps.googleusercontent.com',
    iosBundleId: 'com.example.sociallApp2.RunnerTests',
  );
}
